### ISSUE TITLE
Search not working after update to 1.1.8 or 1.1.9 

### ISSUE THREAD

**Issue by juagarc4** [FACT-Finder-Web-Components/ff-web-components#1]
For one of our customers and following your recommendation for fixing Safari's bug we have updated ff-web-components to the newest version 1.1.9 and the search doesn't work anymore.

On loading the page we receive the follow error:
`
XMLHttpRequest cannot load https://XXXX/XXX/Search.ff?query=M%C3%B6belhandel&channel=xxxx&sid=ecgX9hXxpF5YvtqGP9fPKq1cKvoFiC&queryFromSuggest=true&userInput=M%C3%B6be&format=json Request header field 4b7131634b766f466943 is not allowed by Access-Control-Allow-Headers in preflight response.`

Notes: 
1.- The version 1.1.8 give us the same error.

2.- However if we use the old version of element.build.js withn the new files of 1.1.9, then the search works as expected, but with the bug by Safari.

Can you help us to resolve this problem?
Thanks in advance

**Comment by HJK181** [comment]
Hi,

can you please send and email to 'webcomponents@fact-finder.de' with the URL to your FACT-Finder installation? I assume it is a FACT-Finder configuration problem.

**Comment by juagarc4** [comment]
Ok. Thank you.
