### ISSUE TITLE
Touch event propagation

### ISSUE THREAD

**Issue by janfeldmann** [FACT-Finder-Web-Components/ff-web-components#14]
* FACT-Finder-Web-Components Magento2-Module:
  1.2.16
* Magento edition and version:
  Magento EE 2.2.8
* PHP version:
  7.1.0
* Expected behavior:
  
  * Touch on `<label for="inputId">` triggers checked-state/ focus of `<input id="inputId">`
* Actual behavior:
  
  * Touch event does not propagate and the corresponding input is not focused / checked

* Additional information
  
  * it only occurs on specific user agents (e.g. iOS iPad Air 12.0)

**Comment by a-laurowski** [comment]
Hi @janfeldmann 
Could You please give us additional information which may be helpful with finding the reason and solution of that undesirable behaviour?

- How can we reproduce it/In which part of application does it occurs?
- Which web browser do You use on IPad?

**Comment by omikron-fp** [comment]
Hello @janfeldmann,
We haven't heard from you in a while. Assuming the issue is no longer relevant.
Please do not hesitate to reopen it if the issue still exists.
