### ISSUE TITLE
ff-suggest-item view breaks on trailing space

### ISSUE THREAD

**Issue by ghost** [FACT-Finder-Web-Components/ff-web-components#15]
There's an issue while searching for a term.

First of all, these combinations of the search term(s) work:
**[searchterm]** and **[searchterm]_[nextsearchterm]**.

Here a screenshot of the working example:
![ff-web-components-before-trailing-space](https://user-images.githubusercontent.com/40581889/55085267-ac7a4c00-50a6-11e9-90ed-5c94eb22c6a7.jpg)

If the search input field contains **one term and an additional space** (trailing space), the view breaks. (e.g. **[searchterm]** and **[searchterm]_** ( **_** means trailing space in this case ))
![ff-web-components-after-trailing-space](https://user-images.githubusercontent.com/40581889/55085285-b3a15a00-50a6-11e9-8190-ebc70a92c3df.jpg)

Did anyone run into this issue or is able to reproduce it?
Any help is much appreciated.

**Comment by omikron-fp** [comment]
Hi @ca1zr,
Thank you for the bug report. I was able to reproduce it.
Bugfix is queued.

Judging from your markup you are still on WebComponents `1.x`. Please consider updating to `3.x` for new features and overall better performance.

**Comment by omikron-fp** [comment]
Hi @ca1zr,
Fix is implemented. We are going to release it together with some other improvements approximately next week.

**Comment by omikron-fp** [comment]
Hi @ca1zr,
The fix has been released with version [3.3.0](https://github.com/FACT-Finder-Web-Components/ff-web-components/releases/tag/3.3.0).

Thank you for your patience.
