### ISSUE TITLE
Some components throw DOMExceptions

### ISSUE THREAD

**Issue by DaSchTour** [FACT-Finder-Web-Components/ff-web-components#20]
When including `<ff-asn>` or `<ff-paging>` into an angular application it throws a

> Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes

which seams to be caused by setting attributes on the component to early in the lifecycle, as described here: https://stackoverflow.com/questions/43836886/failed-to-construct-customelement-error-when-javascript-file-is-placed-in-head

**Comment by toarm** [comment]
Hi @DaSchTour 
thanks for reporting that issue. I could reproduce it using `document.createElement("ff-asn/ff-paging")`.

The fix is currently in QA and will most likely be published with our next release by the end of this week.

**Comment by toarm** [comment]
for reference FFWEB-1257

**Comment by omikron-fp** [comment]
Fix released in [3.4.0](https://github.com/FACT-Finder-Web-Components/ff-web-components/releases/tag/3.4.0)

**Comment by DaSchTour** [comment]
After testing the new release if've seen that `ff-asn` and `ff-paging` are working correctly but`<ff-paging-item>` throws DOMException.

**Comment by omikron-fp** [comment]
We will take care of it. Sorry for the inconvenience.

**Comment by toarm** [comment]
PR is in review again:
FFWEB-1257 fix ff-sortbox dom exception
FFWEB-1257 fix ff-paging-dropdown dom exception
FFWEB-1257 fix ff-products-per-page-dropdown dom exception
FFWEB-1257 fix ff-prodcuts-per-page-list dom exception
FFWEB-1257 fix ff-products-per-page-select dom exception
FFWEB-1257 fix ff-paging-item dom exception
FFWEB-1257 fix ff-campaign-feedbacktext dom exception

The new test should cover all elements now.  We will publish a new release soon

**Comment by toarm** [comment]
fixed https://github.com/FACT-Finder-Web-Components/ff-web-components/releases/tag/3.5.0
