### ISSUE TITLE
Applied filters component

### ISSUE THREAD

**Issue by mwinkelm** [FACT-Finder-Web-Components/ff-web-components#21]
I'm wondering if you have plans to add a component that lists all applied filters and from where you can deselect them too?

Random example from Media Markt:

![applied-filters](https://user-images.githubusercontent.com/6881829/60715880-6262fb00-9f1e-11e9-9cbf-37f0c592c8eb.png)

**Comment by mwinkelm** [comment]
Hm .. obviously this is doable when I have a look at toom.de. But how is this done?

**Comment by toarm** [comment]
We are implementing it atm.
Here is the spec: 
https://github.com/FACT-Finder-Web-Components/feature-lab/blob/ff-filter-cloud/specs/ff-asn-selected-filter-cloud/ff-asn-selected-filter-cloud.md

**Comment by toarm** [comment]
You could implement it on your own with a `ResultDispatcher.addCallback("asn" (groups) => {}` callback. 
Just bare in mind that groups is a reference to the data passed to `<ff-asn>` element. 
Iterate through all groups and gather all elements from `selectedElements` array and `splice` a new group into the `groups` array. 
Or just wait approx 1-2 weeks until `<ff-filter-cloud>` is released. (provided the spec above suits your need)

**Comment by mwinkelm** [comment]
@toarm Any news on this one? When do you plan to release this feature?

**Comment by toarm** [comment]
@mwinkelm 
Now that #19 is on its way we start developing this feature. Im sorry for the inaccurate estimation. Development shouldnt take long but with QA and releasing it might be the week after next.

**Comment by mwinkelm** [comment]
@toarm Thanks for the update. We are currently not in a hurry, so we‘ll just be patient for the feature‘s release. Keep up the good work!

**Comment by KPS-DB** [comment]
@toarm Could you please update this ticket, preferably with a solution = closed ;-)

**Comment by omikron-fp** [comment]
Hello @KPS-DB, the component is currently under review. It will probably be ready for beta release next week.

**Comment by omikron-fp** [comment]
@KPS-DB @mwinkelm 
Beta release is now available.
https://github.com/FACT-Finder-Web-Components/ff-web-components/releases/tag/3.7.0-filter-cloud.1

**Comment by omikron-fp** [comment]
@mwinkelm @KPS-DB any feedback on this feature? We are going to merge it soon.

**Comment by omikron-fp** [comment]
Merge of feature is planned for tomorrow.
FYI @mwinkelm @KPS-DB

**Comment by mwinkelm** [comment]
Hi @omikron-fp, sorry for not responding. Had no time to test the beta so far. But i'm sure it will work ;-)

**Comment by omikron-fp** [comment]
Feature released in [3.8.0](https://github.com/FACT-Finder-Web-Components/ff-web-components/releases/tag/3.8.0)
