### ISSUE TITLE
New feature: Search within filters

### ISSUE THREAD

**Issue by mwinkelm** [FACT-Finder-Web-Components/ff-web-components#22]
Hi! The following is a feature request.

The client where we are currently using the web components also wants to use the brand filter. But the list of brands is massive (150+ entries), so that from a usability point of view just the "see all" link is not suitable for a good user experience. For these cases it would be good to have the possibility to setup a search functionality within a filter so that the user can easily find entries in a filter.

Additional idea: Maybe besides a boolean flag which indicates to use a search field or not, also a threshold value could be useful. As an example: If the filter brands has more than 30 entries, then show a search box, if it is lower, never show it. The value 30 is configurable then.

**Comment by ghost** [comment]
Thanks for your feedback and idea! I have created internal feature request ticket FFWEB-1324 for internal discussion. We will let you know about any progress.

**Comment by toarm** [comment]
I'd like to start the spec process for this feature soon @omikron-fp 
Would be nice to see this getting implemented during my august vacation

**Comment by omikron-fp** [comment]
Hi @mwinkelm,
The initial draft for this feature's specifications is out. You can take a peek here:
https://github.com/FACT-Finder-Web-Components/feature-lab/pull/3
Comments are more than welcome.

**Comment by omikron-fp** [comment]
Specifications are [complete](https://github.com/FACT-Finder-Web-Components/feature-lab/blob/searchable-asn-group/specs/searchable-asn-group/searchable-asn-group.md). Feature is queued for implementation.

**Comment by omikron-fp** [comment]
Feature is currently being developed. A first beta release should be available within two weeks from now.

**Comment by omikron-fp** [comment]
Feature is now available in pre-release [3.7.0-searchable-asn-groups.1](https://github.com/FACT-Finder-Web-Components/ff-web-components/releases/tag/3.7.0-searchable-asn-groups.1)
See [specifications](https://github.com/FACT-Finder-Web-Components/feature-lab/blob/searchable-asn-group/specs/searchable-asn-group/searchable-asn-group.md) for details.
Feedback welcome!

**Comment by omikron-fp** [comment]
@mwinkelm, feature is merged into master and will be available after the next release.

**Comment by toarm** [comment]
released https://github.com/FACT-Finder-Web-Components/ff-web-components/releases/tag/3.9.0
