### ISSUE TITLE
How to utilize opened attribute on ff-asn-group

### ISSUE THREAD

**Issue by mwinkelm** [FACT-Finder-Web-Components/ff-web-components#25]
I have the following use case: 

**I want to have the ff-asn component behave like so:** On initial page load, the first three (or whatever I want to configure) `ff-asn-group` elements get the `opened` attribute. The rest doesn't, so that they are initially closed. 

What is the current behaviour of the attribute `opened` and can it be used for this scenario? I can not set this to categories specifically (e.g. at `ff-asn-group` with `for-group="Color"`) as the position can be rearranged in the FACT-Finder back-end.

Thanks,
Markus

**Comment by toarm** [comment]
Hi @mwinkelm ,
you cant use the opened attribute this way, unfortunatley. 
The code snippet below will work, as long as all immediate children are `ff-asn-group` or `ff-asn-group-slider` elements
```html
        </ff-asn>
        <script>
            document.querySelector("ff-asn").addEventListener("dom-updated", function () {
                const showAnimation = false;
                const children = document.querySelector("ff-asn").children;
                for (let i = 0; i < 3; i++) {
                    const asnGroup = children[i];
                    if (asnGroup)
                        asnGroup.show(showAnimation);
                }
            })
        </script>
```

**Comment by mwinkelm** [comment]
Ah, now I have a use case for the dom-updated callback. Thanks for pointing me in the right direction.

Internally we discussed this again and looked at the demo of the web components to figure out the default behaviour of this feature. Is it correct, that the components remember their state so that the user is over full control of the open / closed state of each filter? One exception: When the user closes a filter that has an active entry, this will be reopened again if the dom is updated?!

**Comment by toarm** [comment]
> One exception: When the user closes a filter that has an active entry, this will be reopened again if the dom is updated

That's the default case, yes. But only if filters are active otherwise the group stays closed.
