### ISSUE TITLE
span in search result does not render

### ISSUE THREAD

**Issue by unsignedmind** [FACT-Finder-Web-Components/ff-web-components#28]
Hello,
I am using ff-web-components@3.10.0 and I have implemented the functionality for searchable asn filters. The search results are wrapped in a span tag, but the span tag itself is not rendered. 

Is this a bug or must the search results be implemented otherwise?

This is what i added to our filter component:
```HTML
<ff-asn #ffAsnElement searchable-from="31">
  .....
```
```HTML
<div class="ffw-wrapper">
  <div slot="filterSearch" class="filter-search__wrapper">
    <input class="filter-search__input" placeholder="Search">
  </div>
</div>
```

Rendered HTML:
![image](https://user-images.githubusercontent.com/28564258/69731032-6db2ff00-1129-11ea-802e-89ef112b2cae.png)

**Comment by omikron-fp** [comment]
Hello @unsignedmind,
That is the markup of the hit-highlighting. This usually happens when double mustaches `{{ }}` are used in a custom template instead of triples `{{{ }}}` for the data binding.
I guess you are using double mustaches in your custom template of `ff-asn-group-element`. Please double-check.
More info on the template engine can be found [here](https://web-components.fact-finder.de/documentation/3.x/template-engine).

Let us know if switching to `{{{ }}}` fixes the problem.
Kind regards

**Comment by unsignedmind** [comment]
Currently this template looks like this. We use brackets for data binding. I guess I need to define a custom template for the search results, don't I? Tripple [[[]]] didn't work.
```HTML
<ff-asn-group-element>
      <button type="button" slot="selected" class="filter-element filter-element--selected">
        <span class="filter-element__name">
          <span class="filter-element__label">[[element.name]]</span>[[#element.recordCount]]<span
            class="filter-element__count"
            >([[element.recordCount]])</span
          >[[/element.recordCount]]
        </span>
        <span class="switch show-for-xxlarge">
          <input type="checkbox" class="switch__input" checked tabindex="-1" />
          <span class="switch__appearance"></span>
        </span>
      </button>
      <button type="button" slot="unselected" class="filter-element">
        <span class="filter-element__name">
          <span class="filter-element__label">[[element.name]]</span
          ><span class="filter-element__count">([[element.recordCount]])</span>
        </span>
        <span class="switch show-for-xxlarge">
          <input type="checkbox" class="switch__input" tabindex="-1" />
          <span class="switch__appearance"></span>
        </span>
      </button>
    </ff-asn-group-element>
```

**Comment by omikron-fp** [comment]
I see. You are using the `mustache-delimiters` attribute, right?
In that case adding another pair of curly braces should work.
```html
<!-- current -->
<span class="filter-element__label">[[element.name]]</span>

<!-- with HTML rendering -->
<span class="filter-element__label">[[{element.name}]]</span>
```

**Comment by unsignedmind** [comment]
My Page does not load completely if I surround element.name with curly braces. IntelliJ told me to escape it like shown. Now the element.name does not render. I don't know if it's because this is an angular project.
```HTML
<span class="filter-element__label">[[{{element.name}]]</span>
```

**Comment by omikron-fp** [comment]
That's odd. We have certainly seen the `[[{element.name}]]` notation work in an angular project.
When used like this and the page doesn't load completely, is there are warning or error in the console?

**Comment by unsignedmind** [comment]
That's the error when i add the curly braces `<span class="filter-element__label">[[{element.name}]]</span>` I see the blue color we gave to the body tag, but nothing else renders.
```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("
    </ff-asn-group-element>
  </ff-asn-group>
</ff-asn>
[ERROR ->]"): ng:///FilterModule/FilterGroupsComponent.html@77:0
Invalid ICU message. Missing '}'. ("
    </ff-asn-group-element>
  </ff-asn-group>
</ff-asn>
```

**Comment by unsignedmind** [comment]
If I leave the [[]] as they are and don't search, the filter options are displayed as they should be.

**Comment by omikron-fp** [comment]
Yes, that is expected as there is no search string to be highlighted.
If you type `oo`, the "Kitchen tools" item should be rendered as
```
Kitchen t<span class="ffw-query">oo</span>ls
```

**Comment by unsignedmind** [comment]
Yes that's the current output.
![image](https://user-images.githubusercontent.com/28564258/69738364-49115400-1136-11ea-8b23-1ddee1df79b8.png)

Do I need to add the HTML for the highlighting to the custom template?

**Comment by omikron-fp** [comment]
No, it's added automatically. But because we have double brackets here, the template engine interprets the added `span` HTML as a verbatim string. This is usually fixed by using triple curly braces which tells the engine to interpret the string as HTML.
Unfortunately, the clashes with angular which also uses double curly braces for data binding.

Just to make sure, you are setting the `<ff-communication mustache-delimiters="[[,]]">` attribute, aren't you?

**Comment by unsignedmind** [comment]
Yes `mustache-delimiters` are set to `[[,]]`

**Comment by omikron-fp** [comment]
OK, we will have to dig a little deeper here.
Unfortunately, I can't provide you with a workaround for the time being.
We will come back to you.

**Comment by unsignedmind** [comment]
Okay thanks!

**Comment by omikron-fp** [comment]
Just another quick one. Could you try the following?
```html
<span ngNonBindable class="filter-element__label">{{{element.name}}}</span>
```
Note that it is `{{{` instead of `[[{`.

**Comment by unsignedmind** [comment]
I just left. I'll try and reply tomorrow

**Comment by unsignedmind** [comment]
That is the solution! Thanks for the help.

**Comment by unsignedmind** [comment]
One more question. 
How do I add a group name to the placeholder attribute. For example placeholder="Search for {{{group.name}}}"

**Comment by omikron-fp** [comment]
Glad it helped!

Regarding your question. Data binding is currently not supported in the `<div slot="filterSearch">` context. But it would be very easy to implement.
I'll create an internal issue. Chances are good the data binding will be available in the next release.

**Comment by unsignedmind** [comment]
Okay thank you for the information. Is there a planned date for the next release?

**Comment by omikron-fp** [comment]
Nothing planned but sometime next week is reasonable I think.

**Comment by omikron-fp** [comment]
FYI: We just merged the data binding into master. Going to release it next week.

**Comment by mwinkelm** [comment]
@omikron-fp Will we get the release as a "Nikolaus present"? ;-)

**Comment by omikron-fp** [comment]
@mwinkelm I very much think so. We are fixing a critical issue at this very moment. We are pushing for a release at about 1530 today.

**Comment by omikron-fp** [comment]
I hope you polished your boots well!
https://github.com/FACT-Finder-Web-Components/ff-web-components/releases/tag/3.11.0
