### ISSUE TITLE
Angular component resolution (<mat-icon>) in ff-filter-cloud

### ISSUE THREAD

**Issue by mwinkelm** [FACT-Finder-Web-Components/ff-web-components#29]
Hi,

we're using the `<mat-icon>` component from Angular Material in our project for displaying icons. This works like a charm for example in the fact finder component `ff-asn-remove-all-filter`:
```
<ff-asn-remove-all-filter show-always="true" ...>
  <button>
    <mat-icon svgIcon="clear"></mat-icon>
  </button>
</ff-asn-remove-all-filter>
```
However it does not work with the newly introduced `ff-filter-cloud` component, like so:
```
<ff-filter-cloud>
  <button data-template="filter">
    <mat-icon svgIcon="close"></mat-icon>
  </button>
</ff-filter-cloud>
```
Maybe you can try to reproduce this with https://material.angular.io/components/icon/overview and check if this is a bug in `ff-filter-cloud`?

Thanks,
Markus

**Comment by omikron-fp** [comment]
Hi @mwinkelm,

This probably happens because `ff-filter-cloud` clones the `data-template` multiple times. `ff-asn-remove-all-filter` doesn't need to do this.

We will look into this issue and see what we can do about it.

**Comment by DaSchTour** [comment]
I think we can solve this by registering some of our angular components as web components which then should be save for any DOM manipulation.

**Comment by omikron-fp** [comment]
Although I haven't tried it, it sounds a lot as if it could work. And it potentially gives you more control over individual components.

There might also be another approach: All elements emit a `dom-updated` event. Perhaps it's possible to listen on it and initialise `mat-icon` manually. That is, if it can be initialised like that.

For reference, `dom-updated` in the [documentation](https://web-components.fact-finder.de/api/3.x/ff-filter-cloud#tab=api).
And a [usage example](https://github.com/FACT-Finder-Web-Components/demos/blob/release/3.x/ff-record-list-3d/index.html#L54) of it. It's not `ff-filter-cloud` but hopefully enough to get the gist of if.

**Comment by mwinkelm** [comment]
This particular problem could be solved with the strategy @DaSchTour mentioned. Thanks for your investigation and hints for additional potential solutions.
