### ISSUE TITLE
Webcomponents breaks Event Object in IE

### ISSUE THREAD

**Issue by wesseloh-as** [FACT-Finder-Web-Components/ff-web-components#3]
_prototype.js_ extends native `Event` Object with it's own Methods, like `Event.observe`.

Webcomponents seems to replace the whole `Event` object with it's own implementation.

That breaks _prototype.js_ which breaks Magento in our case.

**Comment by toarm** [comment]
Can you please provide a bit more information?

* Which protopye.js version are you using.
* What are you trying to do?
* A small as possible code snippet to reproduce your error somehow
* Is this issue related to an event fired by our web components or does it break an completly unrelated event somewhere else?

I'm not quite familiar with prototype.js but maybe there is a way to extend a single event manually with prototype.js?

**Comment by wesseloh-as** [comment]
* our _prototype.js_ Version is: v1.7 inside Magento v1.9.3.8

* you don't have to do anything besides loading a page with webcomponents on it. In our case FF webcomponents on the search results page of a Magento shop.

* actually the problem is not caused by fact-finder module itself. The problem is introduced by webcomponents (polyfill) module that is used by fact-finder as dependency.


_prototype.js_ extends the native `Event` object, here is a snippet:

```javascript
  Object.extend(Event, {
    fire:          fire,
    observe:       observe,
    stopObserving: stopObserving,
    on:            on
  });
```

In case of IE, webcomponents polyfill replaces the entire `Event` object even if it exists.

Before webcomponents is loaded (we see a native Object):

![image](https://user-images.githubusercontent.com/37796455/39355990-1897b6c4-4a0f-11e8-8e73-3b89cb217409.png)

After webcomponents has been loaded (we see a customized constructor function):

![image](https://user-images.githubusercontent.com/37796455/39356017-385edb40-4a0f-11e8-8461-45798ccb993d.png)

That means all methods and properties added by _prototype.js_ are gone.
This breaks anything else that depends on _prototype.js_.

**Comment by toarm** [comment]
I have no idea about the loading order of your scripts but reversing the order could fix this. 
In case you are loading `webcomponents-lite.min.js` first, just try to load `prototype.js` first or vice versa.

If both scripts are loaded via `<script>` tag without the `async` attribute it should be enough to switch the lines. If you are loading any of these scripts `async` you should rely on onload to be 100% sure.

**Comment by wesseloh-as** [comment]
You are right, that switching the order may solve the problem.

But we can't change the way Magento loads and manages resources.
Those are defined in xml configuration files per module.
The only way it would be possible, if we modify core files and it is not an option.

I have fixed that problem (temporarily I hope) with restoring some methods after webcomponents is loaded, but it's not a nice solution too.
