### ISSUE TITLE
Errors while setting configuration are misleading

### ISSUE THREAD

**Issue by DaSchTour** [FACT-Finder-Web-Components/ff-web-components#32]
Configuration of fact finder web components behaves very strange. I had `ff-communication` with some configuration and tried to add some dynamic parameters programmatically through `globalSearchParameter` and `globalCommunicationParameter`, but It seams that if the `ff-communication` is part of the DOM before fact finder scripts are loaded the configuration is not set. So I tried to move it to completely to programmatic setting configuration.
But trying to set the version parameter to `ng` I get the following error
```
Error: Requested NG API version  is not supported by this version of WebComponents. Choose one of [latest, v3, v2] or try updating your WebComponents.
```

I'm using the newest version 3.11.5 of fact finder web components. If I set the value to `latest` it sometimes works and sometimes sends a warning with `Global search parameter 'version' has invalid format.` followed by `Required search params are not available:`. So this seams to be very unstable.

**Comment by DaSchTour** [comment]
I found the issue. When using ng and not setting the configuration through the component I have to also set the ngApi property. Now it works.

**Comment by omikron-fp** [comment]
Is there a way we can improve error messages/documentation to locate the source of error more easily?
Perhaps mentioning the `api` property on `ff-communication` in the error message you reported.
```
Error: Requested NG API version () is not supported by this version of WebComponents. Choose one of [latest, v3, v2] for the 'api' attribute on 'ff-communication' or try updating your WebComponents.
```

**Comment by DaSchTour** [comment]
Well this issue only occures when not using `ff-communication` (or adding it to the DOM to late) because in this case the `ngApi` property is not set. In other cases when having `ff-communication` it defaults to `latest`. So possibly check if `ngApi` is set and reporting an error like: "you need to set ngApi property if you use version: ng"

**Comment by omikron-fp** [comment]
Thank you for the feedback. We'll adjust the error message accordingly.
