### ISSUE TITLE
Make ff-asn-group[for-group] target associatedFieldName

### ISSUE THREAD

**Issue by omikron-fp** [FACT-Finder-Web-Components/ff-web-components#35]
## Problem

`ff-asn-group` templates can be configured to target specific ASN groups/facets through the `for-group` attribute.

```html
<ff-asn-group for-group="Manufacturer">  <!-- in other channels this might be called 'Hersteller" or 'Fabricant' -->
```

Currently, the specified value must match the group's _display name_.
This is problematic in multi-language environments (often realised through multiple FACT-Finder channels) because display names are likely to be different. For each language and group you have to configure a separate template. Typically, the only difference would be the `for-group` value.

Being able to specify an id-like value that is constant across all channels would make definitions of group templates independent from the localised display name and subsequently make multiple definitions redundant.
This id-like value would be `associatedFieldName`.

There is a workaround mentioned in #34.

## Breaking Change

Make `ff-asn-group`'s `for-group` attribute reference the group's `associatedFieldName`.

This constitutes a **breaking change** as _associatedFieldNames_ are very likely to be different from the _display names_.

~~Alternative approaches would be to introduce a separate attribute and deprecate `for-group`. However, `for-group` seems to be the most suitable name. Furthermore, referencing _display names_ is not a good approach to begin with and it doesn't appear worth maintaining.~~

| Chance of being affected | Required effort to fix |
| --- | --- |
| VERY HIGH | LOW |

**Comment by mwinkelm** [comment]
_Just a note to this proposal:_ I have a situation in my current project where a multi select filter also has different values in `associatedFieldName` depending on the combination of selected options of the filter. ~~So, again no way to target this with CSS in a predictable way.~~ Ok, maybe something like `[for-group*="baseAssociatedFieldName"]` works.

**Comment by omikron-fp** [comment]
I think the inconsistent `associatedFieldName` only appears in category/tree-style filters and is is a result of WebComponents transforming the FACT-Finder NG response data to the old FF `7.3` format. This was a requirement for compatibility reasons. 

In tree-style filters the most basic `associatedFieldName` should be `...ROOT` (e.g. `CategoryROOT`).
I see two possiblities for `[for-group]` to target:
1. `[for-group="CategoryROOT"]` - this would be closer to the actual (FF 7.3) response format as is currently provided by WebComponents
2. `[for-group="Category"]` - omits the somewhat obscure `ROOT` part but might be not as intuitive to map by eye

_Side note:_
We are also working on a concept for a WebComponents version that leaves the NG response unmodified (this will be a separate proposal coming soon).
The unmodified FF NG response seems to be consistent in its `associatedFieldName`.
