### ISSUE TITLE
IE error when using template strings in onclick

### ISSUE THREAD

**Issue by wesseloh-as** [FACT-Finder-Web-Components/ff-web-components#4]
when using template strings inside onclick, like this:

```html
<a href="..." onclick="updateQty({{id}})">...
```
IE throws an Error: "[SCRIPT1028](https://docs.microsoft.com/en-us/scripting/javascript/misc/expected-identifier-string-or-number): Expected identifier, string or number / Bezeichner, Zeichenfolge oder Zahl erwartet"

**Comment by toarm** [comment]
Hi @wesseloh-as ,
this is nothing we can fix but here is a proper workaround:
```html
<script>
    function updateQty(element) {
        var id = element.getAttribute("data-id");
        console.log(id);
    }
</script>
<a href="..." onclick="updateQty(this)" data-id="{{id}})">
```
I hope that helps!

**Comment by toarm** [comment]
Feel free to reopen the issue if the solution above is not suitable for you...

**Comment by wesseloh-as** [comment]
Thanks for suggestion (can stay closed).
