### ISSUE TITLE
Slider does not work after first search

### ISSUE THREAD

**Issue by Taxel** [FACT-Finder-Web-Components/ff-web-components#43]
I am having a problem with the asn-group-slider, which is not working for categories with spaces in them (at least that's what I think, the reason might be different but definitely has to do with URI encoding).
When using the slider for the first time, everything works:
In the search event, the filter is added to the existing filters like so:
`filterLeistung%20RMS%20%28Watt%29: "3205-9000"`.

When I now use the slider a second time, a second key is added to the search event like so:
`filterLeistung%20RMS%20%28Watt%29: "2124-9000"
filterLeistung+RMS+%28Watt%29: "3205-9000"`

As far as I can tell, the search then prefers the old value, which makes the slider unusable as long as one does not reset it (removing the keys from the event), then it can be set to a different value again.

I tried url encoding/replacing the string, so only ever `filterLeistung+RMS+%28Watt%29` is set in the event and even deleting the old key, but it does not work and without better documentation for the events it is really just digging in the dark.

Could you tell me a workaround for this (how the event key should be formatted so this works correctly) or fix this issue in the Javascript?

**Comment by omikron-fp** [comment]
Hi @Taxel, sorry for the inconvenience. Could you tell us which versions of WebComponents and FACT-Finder you are using?

**Comment by Taxel** [comment]
I am using Fact-Finder 7.3 with the oxid eshop module and the latest JavaScript from this github repo.

**Comment by omikron-fp** [comment]
Thanks. We will come back to you shortly.

**Comment by omikron-fp** [comment]
Hi @Taxel, this seems to be a bug in the library. A bug ticket is scheduled and we will release a new version as soon as possible.

**Comment by Taxel** [comment]
Thanks for the update, I will wait for the next version then.

**Comment by omikron-fp** [comment]
Hi @Taxel, we just merged a fix to this issue. We are targeting a release for next week.

**Comment by omikron-fp** [comment]
Hi @Taxel, the fix to this issue has been released as `3.15.6`.
https://github.com/FACT-Finder-Web-Components/ff-web-components/releases/tag/3.15.6
Thank you for your patience.
