### ISSUE TITLE
ff-asn-group.show() does not toggle the opened attribute

### ISSUE THREAD

**Issue by Taxel** [FACT-Finder-Web-Components/ff-web-components#45]
I want to open the first five filters by default. 
For this I am calling the `.show()` method on the `ff-asn-group` elements on the `ff-asn`'s dom-updated method like so:

```
$("#ff-asn").on("dom-updated", function(event){
        const childNodes = event.target.childNodes;
        let i = 0;
        for(const cn of childNodes){
            if(cn.localName === "ff-asn-group" || cn.localName === "ff-asn-group-slider"){
                cn.show(true);
                cn.setAttribute("opened", '') // here I am trying to set the opened attribute by hand, but this does not work...
                i++;
                // show only the first 5 filters
                if(i > 4){
                    break;
                }
            }
        }
    });
```
This is working fine, except that the arrows (where CSS switches the transform.rotation based on the [opened] attribute) in the header of each filter group are not rotated correctly, since the attribute is not set.

I suspect this might be unintended behavior for the show() method.

**Comment by a-laurowski** [comment]
Hi @Taxel 
Have you try to set the `opened` attribute directly in a template? According to documentation
 https://web-components.fact-finder.de/api/3.x/ff-asn#tab=api 
you can simply put `<ff-asn-group  for-group="GROUP_NAME" opened>`. To get know about what should be put in a place of GROUP_NAME you can inspect the FACT-Finder response  or the `factfinder.communication.EventAggregator.currentSearchResult` object which is available globally.  The `groups` field should be there.

**Comment by Taxel** [comment]
Haven't tried it yet but that's a nice workaround.
It is a bit different going from "the first five filters are always open" to "these specific filters are always open" but should suffice for our shop (since when I'm rendering the templates in PHP, I don't have access to the FF data).

I'm leaving this open as a bug report until it's confirmed that the show() function of a ff-asn-group should not set the opened attribute.

**Comment by omikron-fp** [comment]
Hi @Taxel, this is a timing issue related to the DOM update cycle.
Wrap your script in a `setTimeout` and you should be fine.
```js
$("#ff-asn").on("dom-updated", function(event){
    setTimeout(() => {
        const childNodes = event.target.childNodes;
        let i = 0;
        for (const cn of childNodes) {
            if (cn.localName === "ff-asn-group" || cn.localName === "ff-asn-group-slider") {
                cn.show(true);
                // cn.setAttribute("opened", '') // not needed
                i++;
                // show only the first 5 filters
                if (i > 4) {
                    break;
                }
            }
        }
    });
});
```

**Comment by Taxel** [comment]
That worked perfectly, thanks!
