### ISSUE TITLE
Rebuild bundle with polyfill

### ISSUE THREAD

**Issue by Taxel** [FACT-Finder-Web-Components/ff-web-components#51]
Hi there,

I am using the latest ff-webcomponents js, which I copied into the oxid6 module in order to update it.
It seems like the webcomponents-sd-cd-pf.js, which is loaded by the module in Internet Explorer 11 has not been rebuilt in the last 11 months. I am getting ~60 Javascript errors from this file in IE11, most are like this:
![image](https://user-images.githubusercontent.com/5514725/98533550-6aa21780-2283-11eb-8467-521c772dd974.png)

I hope this is happening because the version is old, so could you please rebuild the bundles?

**Comment by ikswlaur** [comment]
Hi @Taxel 
By oxid6 module you mean our module, right? https://github.com/FACT-Finder-Web-Components/oxid-eshop-module
Currently it uses Web Components 3.15.8 and so far we didn't observe any similar problems with polyfills. Unfortunately I also wasn't able to observe that using latest version 3.15.9 on my local environment. Of course by using IE11.

Can i ask you to check if the same thing occurs for you using 3.15.8? If you already use this version then can you tell us how to reproduce that in our test OXID instance https://oxid-esales.fact-finder.de/

**Comment by a-laurowski** [comment]
Hi @Taxel 
By oxid6 module you mean our module, right? https://github.com/FACT-Finder-Web-Components/oxid-eshop-module
Currently it uses Web Components 3.15.8 and so far we didn't observe any similar problems with polyfills. Unfortunately I also wasn't able to observe that using latest version 3.15.9 on my local environment. Of course by using IE11.

Can i ask you to check if the same thing occurs for you using 3.15.8? If you already use this version then can you tell us how to reproduce that in our test OXID instance https://oxid-esales.fact-finder.de/

**Comment by a-laurowski** [comment]
Hi @Taxel , is this issue still ongoing?

**Comment by a-laurowski** [comment]
I'm closing the ticket due to inactivity
