### ISSUE TITLE
resultDispatcher for similar Products

### ISSUE THREAD

**Issue by mzanier** [FACT-Finder-Web-Components/ff-web-components#53]
It would be nice if there is the same & easy way to modify ff-similar-products results via a resultDispatcher.

We are using the resultDispatcher for example in ff-record-list to display if a product is with/without shipping costs, % Discount Calculations, truncating Productname etc.

Doing the same with ff-similar-products only works with replaceing it by an api call & EventAggregator and displaying it in a ff-record-list

**Comment by omikron-fp** [comment]
Hello @mzanier,
Thank you for your request.

Are you perhaps looking for the `similarProducts` topic of the [ResultDispatcher](https://web-components.fact-finder.de/api/4.x/core-result-dispatcher)?
Adding a data manipulation callback with this topic you can modify incoming similar-products data like you can modify record-list data.
For example:
```js
document.addEventListener(`ffReady`, ({ resultDispatcher }) => {
    resultDispatcher.addCallback(`similarProducts`, response => {
        response.records[0].record.Title = response.records[0].record.Title.toUpperCase();
    });
});
```

**Comment by mzanier** [comment]
Our latest information was that we have to use the EventAggregator, change data in the EventAggregator Callback and then add it into a seperate ff-record-list, due ff-similar-products have a dynamic hash which is only calculated after webcomponents are ready - and thus the listener will not work for 100%

**Comment by omikron-fp** [comment]
Do you have multiple `ff-similar-products` elements on the page? If not, you can use the approach I posted above.

**Comment by mzanier** [comment]
ok cool. works.
maybe it was an issue with an older ff-components version in december - where it didnt worked that way and fransesco told us to use the other approach.
