### ISSUE TITLE
Show childs in tree view as default

### ISSUE THREAD

**Issue by pbov** [FACT-Finder-Web-Components/ff-web-components#55]
It is somehow possible to show some/all childs of an ASN filter group that acts as a tree view, so the user can see all childs of all parents without selecting a parent?

**Comment by omikron-fp** [comment]
Hi @pbov, this is unfortunately not possible at the moment. This is due to the data structure offered by the FACT-Finder API. WebComponents has no influence here.
In case you are considering a feature request, please refer to your contact person at FACT-Finder.
